	<h2><div class="newsby">Michelle&nbsp;11.8.2009</div><span class="dropcap">2</span><span>010 Season</span></h2>
		<p class="newsbody">You will notice that the 2010 event calendar is shorter than previous years. This is for two reasons. The first is to provide ample time to prepare the quality ending we envision and the second is to give a new board the opportunity to design the new campaign, while training to take on the directing responsibilities.<br /><br />We will be modifying the script policy to allow everyone the ability to play at least a portion of every event, depending upon their Script Points and the specific plot that is running.<br /><br />2010 End of Seasons Calendar<br />April 9-11, 2010 (3-Day Event)<br />May 28 - 31, 2010 (4-Day Event)<br />June 12 - 13, 2010 Silver Kingdom Renaissance Festival<br />June 19 - 20, 2010 Silver Kingdom Renaissance Festival<br />September 3 - 6, 2010 (4-Day Event)<br />October 1 - 3, 2010 (3-Day Event)<br /><br />We are hoping to run special module events after the Faire is closed on Saturday, June 11 and Saturday, June 18. In order for us to put our directing resources to this endeavor, we must be certain that the festival has sufficient volunteer labor to run largely without the directors; thus, freeing us up to run the modules. Please contact Meg to volunteer today! For those that volunteer for a significant portion of the faire, the evening module will be free. For those unable to help with the faire, the standard module event fee will apply.</p>

		<p class="newslink"><a href="/forums/viewtopic.php?t=4043">[Discuss]</a></p>

	<h2><div class="newsby">Michelle&nbsp;11.8.2009</div><span class="dropcap">S</span><span>pecial Thanks</span></h2>
		<p class="newsbody">We have enjoyed having such a wonderful support crew of volunteers and enthusiastic players who give freely of their time and resources, month after month. Without all of your contributions, the game would not be as functional or as immersive as it is, by far. Although we can only recognize a few here, you are all very much appreciated and loved!<br /><br />* To Michele C. for being such an awesome co-editor and desktop publisher! You never seem to amaze us with the great cover art you come up with!<br />* To Rob Z. and Lou C. our amazing logistics and storage gurus - how could we ever run the game without you guys! When one is out, the other does double duty - just incredible!<br />* To the 2008, 2009 and 2010 SKRF Committees a special thanks for taking on these time consuming, but necessary roles to keep the SKRF such a success!<br />* To the 2008, 2009 and 2010 Promotions Teams - thanks for taking on such an important role for the marketing and promotion of the game!<br />* To all who arrive early to help setup for the event and all who stay late to help with the event cleanup - a HUGE thanks!<br />* Thanks goes out to the kitchen staff for making such wonderful meals for us! A special thanks goes to Phil H. and Josh B. for taking on the ServSafe training and becoming such leaders in this area for us!<br />* To Ken for crossing over to become SUPER script - THANKS!<br />* To Dave I. for taking on the Safety Coordinator position - THANKS!<br />* To all who have volunteered to help with sewing projects, making weapons, spell packets, banners or any promotions effort - a HUGE Thanks!</p>

		<p class="newslink"><a href="/forums/viewtopic.php?t=4042">[Discuss]</a></p>

	<h2><div class="newsby">Michelle&nbsp;11.8.2009</div><span class="dropcap">C</span><span>losing Out 2009 Season</span></h2>
		<p class="newsbody">We hope everyone has enjoyed the explosive 2-event finale for the 2009 season! The stage was set in the first act of the story, has risen to a climax in the second act and we look forward to the exciting conclusion of this campaign in the 2010 season. <br /><br />But, there are still many more stories to tell and we look forward to working with a new set of directors who will come forward to take the LARP into its next journey. Here are just a few of the varied directions the game and story could take:<br /><br />    * Will the surviving heroes of this campaign against Darkness go on to further glory?<br />    * How do the remnants of the Four Thrones or the Eclipse world shift to survive?<br />    * Will the surviving heroes ever find peace or will they always find themselves perched on the razor's edge, fighting noble causes?<br />    * Will Throne Spirits continue to be powerful in the new age or will the gods rise to power?<br />    * Who is Ullon and what on earth is the Earth Being?<br />    * Did I hear someone say something about an age of demons? Who lived during that age and how did it come to an end?<br />    * Who forms the Empire of L1?<br />    * What happened to the colonists of L2 that didn't jump through the portals to the new world of L3?<br />    * What happened to the surviving heroes of Gat Thurm and who led the world into a new age?<br /><br />The work of a director is intensely demanding, but it is also very rewarding. Imagining a world for others to immerse themselves into and then seeing it become a reality at the events is quite amazing. Digging into the psyches of player characters to see how they will shift given the right paths or pressure can definitely be entertaining! But, seeing how much life comes to the story and the world through the collaboration of players and directors tops it for me! This is an incredible community of creative people and we can't wait to see what comes next! If you are interested in a board position, please send a note to board@lione.net.</p>

		<p class="newslink"><a href="/forums/viewtopic.php?t=4041">[Discuss]</a></p>

	<h2><div class="newsby">Shirley-Ann&nbsp;9.30.2009</div><span class="dropcap">R</span><span>egistration for online forums &amp; programs</span></h2>
		<p class="newsbody">Greetings!<br /><br />Thanks for joining us on the End of Seasons website. There are several interesting online applications available to our players and scripts on this site, and below are some instructions on how to get signed up to make use of them. Access to these programs will allow you to see your updated character information; participate in the in-game and out-of-game community forums; and make use of your character's vocation skills, reputation, and bank account. As always, if you have any questions or concerns feel free to contact us at <span style="font-weight: bold;">board@lione.net</span>. Please be aware, though, that our volunteer Directors are handling multiple projects, and be patient. You will get a response, but it might take a few days.<br /><br />For all registration purposes - from new player creation to the database to the Forums to the Vocation Station - it is very important that you use your complete legal name (i.e., the one on your driver's license). You will also need to have your Player Number (#) handy. This is extremely important as we need to have a consistent record of your legal identity in all of our programs for both logistical and security reasons. This means no nicknames or unofficial names can be accepted. Hyphenated names are fine, but please avoid using periods with your middle initial. For example, \"Jennifer M Clayton-Smith\", player # 999, is acceptable. \"Jenni M. Can'twaitforthenextevent\" is not.<br /><br />As indicated above, you will need to have created a player profile, including a player #, with one of our Directors in order to access the non-public section of the Forums. If you choose to script before creating a character, you should still create a player profile in order to record things such as your earned script points. Your player # is printed on the top of your character card. Each new character you create will be added to your # in this manner: Varg Skullsplitter (999-1), Flicka Flowerpetal (999-2). And whatever you do, please don't actually give any of your characters the above names...they're horrifying, really. <br /><br />Once you have completed your online registration, a Director will look it over and approve it. You can speed this process up by sending a quick email to the Board to let us know that you've filled out the registration form. If several days have passed and you are unable to log in, please contact the Board for assistance and updates.<br /><br />Cheers!<br />Shan &amp; the Board of Directors</p>

		<p class="newslink"><a href="/forums/viewtopic.php?t=4018">[Discuss]</a></p>

	<h2><div class="newsby">Darren&nbsp;6.15.2009</div><span class="dropcap">N</span><span>ew Friends!</span></h2>
		<p class="newsbody">A warm welcome from End of Seasons to all of our new friends made at this year's Silver Kingdom Renaissance Faire!<br /><br />Have a look around on our site and get comfy....peruse the setting and play style information; check out our Resources section and the photo gallery for past events. PDFs of the rules (and some of our plot information) are all on the bottom right hand side of this page.  Additionally, you can just click here: <br /><br /><a href="http://www.lione.net/downloads/EndofSeasonsCoreBook_v1.19.pdf" target="_blank">http://www.lione.net/downloads/EndofSeasonsCoreBook_v1.19.pdf</a> <br /><br />Also if you would like to register for our social and in-game forums, please create a log-in with your full name.  If you have any questions, feel free to drop us an email at board@lione.net. <br /><br />Thanks and welcome aboard!</p>

		<p class="newslink"><a href="/forums/viewtopic.php?t=3945">[Discuss]</a></p>

